### ISSUE TITLE
Pass API key in Skynet-Api-Key header

### ISSUE THREAD

**Issue by Tails** [cerebralcourt/skynet-rs#1]
Currently the API key is passed as Authority as apikey@skynetportal.net/ ..

According to the current SDK docs, it should be passed by HTTP header.

https://sdk.skynetlabs.com/#api-authentication

Thanks for this port!

**Comment by giraffekey** [comment]
Yeah looks like it's outdated. Thanks for the fix!

**Comment by giraffekey** [comment]
Closed by #2
